config/routes.rb
Rails.application.routes.draw do
  

  root 'deliveries#index'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  
  resources :deliveries, only: [:show, :index]
  
  resources :transactions, only: [:new, :create]

  resource :cart, only: [:show] do
  put 'add/:delivery_id', to: 'carts#add', as: :add_to
  put 'remove/:delivery_id', to: 'carts#remove', as: :remove_from
end

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
has_many :purchases
has_many :buyers, through: :purchases
def image
    '../images/#{image_url}'
  end

def cart_action(current_user_id)
  if $redis.sismember "cart#{current_user_id}", id
    "Remove from"
  else
    "Add to"
  end
end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	belongs_to :delivery
belongs_to :buyer, class_name: 'User'
	#def change
    #create_table :purchases do |t|
      #t.integer :delivery_id
      #t.integer :buyer_id
      #t.timestamps
    end
    #add_index :purchases, [:delivery_id, :buyer_id], unique: true
  #end
#end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :purchases, foreign_key: :buyer_id
has_many :deliveries, through: :purchases
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

def cart_count
  $redis.scard "cart#{id}"
end

def cart_total_price
  total_price = 0
  get_cart_deliveries.each { |delivery| total_price+= delivery.price }
  total_price
end
 
def get_cart_deliveries
  cart_ids = $redis.smembers "cart#{id}"
  Delivery.find(cart_ids)
end

def purchase_cart_deliveries!
  get_cart_deliveries.each { |delivery| purchase(delivery) }
  $redis.del "cart#{id}"
end
 
def purchase(delivery)
  deliveries << delivery unless purchase?(delivery)
end
 
def purchase?(delivery)
  deliveries.include?(delivery)
end

FIELDS = [:first_name, :last_name, :phone, :website, :company, :fax, :addresses, :credit_cards, :custom_fields]
  attr_accessor *FIELDS

  def has_payment_info?
    #braintree_customer_id
  end

  def with_braintree_data!
    return self unless has_payment_info?
    braintree_data = Braintree::Customer.find(braintree_customer_id)

    FIELDS.each do |field|
      send(:"#{field}=", braintree_data.send(field))
    end
    self
  end

  def default_credit_card
    return unless has_payment_info?
    credit_cards.find { |cc| cc.default? }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
   before_action :authenticate_user!
 
  def show
    @cart_deliveries = current_user.get_cart_deliveries
  end
 
  def add
    $redis.sadd current_user_cart, params[:delivery_id]
    render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:delivery_id]
    render json: current_user.cart_count, status: 200
  end
 
  private
 
  def current_user_cart
    "cart#{current_user.id}"
  end
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  #before_action :set_delivery, only: [:show, :index]

  # GET /deliveries
  # GET /deliveries.json
  def index
    @deliveries = Delivery.all
  end

  # GET /deliveries/1
  # GET /deliveries/1.json
  def show
    @delivery = Delivery.find(params[:id])
    @cart_action = @delivery.cart_action current_user.try :id
  end
  end

  # GET /deliveries/new
  #def new
    #@delivery = Delivery.new
  #end

  # GET /deliveries/1/edit
  #def edit
  #end

  # POST /deliveries
  # POST /deliveries.json
  #def create
    #@delivery = Delivery.new(delivery_params)

    #respond_to do |format|
      #if @delivery.save
        #format.html { redirect_to @delivery, notice: 'Delivery was successfully created.' }
        #format.json { render :show, status: :created, location: @delivery }
      #else
        #format.html { render :new }
        #format.json { render json: @delivery.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # PATCH/PUT /deliveries/1
  # PATCH/PUT /deliveries/1.json
  #def update
    #respond_to do |format|
      #if @delivery.update(delivery_params)
        #format.html { redirect_to @delivery, notice: 'Delivery was successfully updated.' }
        #format.json { render :show, status: :ok, location: @delivery }
      #else
        #format.html { render :edit }
        #format.json { render json: @delivery.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.json
  #def destroy
    #@delivery.destroy
    #respond_to do |format|
      #format.html { redirect_to deliveries_url, notice: 'Delivery was successfully destroyed.' }
      #format.json { head :no_content }
    #end
  #end

  #private
    # Use callbacks to share common setup or constraints between actions.
    #def set_delivery
      #@delivery = Delivery.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    #def delivery_params
      #params.require(:delivery).permit(:item, :price, :description, :image_url)
    #end
#end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_braintree_data, only: [:show, :edit]

def show
end

  def new
  gon.client_token = generate_client_token
 end
 
 def edit
    @credit_card = current_user.default_credit_card
    @tr_data = edit_customer_tr_data
  end
  
 def create
    unless current_user.has_payment_info?
    @result = Braintree::Transaction.sale(
                amount: current_user.cart_total_price,
                payment_method_nonce: params[:payment_method_nonce],
                customer: {
                  first_name: params[:first_name],
                  last_name: params[:last_name],
                  #company: params[:company],
                  email: current_user.email,
                  phone: params[:phone]
                },
                options: {
                  store_in_vault: true
                })
  else
    @result = Braintree::Transaction.sale(
              amount: current_user.cart_total_price,
              payment_method_nonce: params[:payment_method_nonce])
    end
    if @result.success?
      #current_user.update(braintree_customer_id: @result.transaction.customer_details.id) unless current_user.has_payment_info?
    current_user.purchase_cart_deliveries!
    redirect_to root_url, notice: "Congraulations! Your transaction has been successfull!"
  else
    flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
    gon.client_token = generate_client_token
    render :new
  end
  end

private
def generate_client_token
  if current_user.has_payment_info?
    Braintree::ClientToken.generate(customer_id: current_user.braintree_customer_id)
  else
    Braintree::ClientToken.generate
  end

#def check_cart
    #if current_user.get_cart_deliveries.blank?
      #redirect_to root_url, alert: "Please add some items to your cart before processing your transaction!"
    #end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/carts/show.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>My Cart</h4>
    <p class="mb0"> You've selected <span class="cart-count"><%=current_user.cart_count%></span> deliveries!</p>
  </div>
 
  <% @cart_deliveries.each do |delivery|%>
  <div data-equalizer class="cart-delivery large-12 column mb1">
    <div class="column large-2 text-center p0" data-equalizer-watch>
      <%=link_to delivery do%>
        <%=image_tag delivery.image_url, class: "radius-l1"%>
      <%end%>
    </div>
    <div class="column large-7 glassy-bg text-center" data-equalizer-watch>
        <p class="scale ptm"> <%= delivery.item %> </p>
    </div>
    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>
      <%=link_to "" , data: {targetUrl: remove_from_cart_path(delivery)} do%>
        <i class="fi-x right"></i>
      <%end%>
      <h4 class="scale">$ <%= delivery.price %></h4>
    </div>
  </div>
  <%end%>
  <%=link_to "Checkout", new_transaction_path, class: "button" unless current_user.get_cart_deliveries.blank?%>

</div>

app/views/deliveries/index.html.erb
<!--p id="notice"><%= notice %></p-->

<h4 class="column">Featured Deliveries</h4>
<div class=column">
<ul class="deliveries-grid no-bullet row">
    <% @deliveries.each do |delivery| %>
    <li class="larg-3 medium-4 small-12 column">
      <div class="delivery-card padly">
      <%= link_to delivery, class: "image" do %>
      <%= image_tag delivery.image_url%>
      <% end %>
      <div class="delivery-info ell glassy-bg padmy padlx">
      <div class="item">
      <h6><%= delivery.item %></h6>
      </div>
      <p class="left price label delivery-label radius">$ <%= delivery.price %></p>
      </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/deliveries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="large-3 small-12 column">
  <%=image_tag @delivery.image_url%>
</div>
 
<div class="large-9 small-12 column">
  <h3>
    <%= @delivery.item %>
  </h3>
  <p class="label delivery-label radius mb1">
      <%= (current_user && current_user.purchase?(@delivery)) ? "Purchased" : "$#{@delivery.price}" %>
    </p>
 
  <p><%= @delivery.description %></p>
  <%if signed_in?%>
  <%=link_to "", class: "button", data: {target: @cart_action, addUrl: add_to_cart_path(@delivery), removeUrl: remove_from_cart_path(@delivery)} do%>
    <i class="fi-shopping-cart"></i>
    <span><%=@cart_action%></span> Cart
  <%end%>
<%end%>
</div>
<%= link_to 'Back', deliveries_path %>

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="row">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>

app/views/layouts/_header.html.erb
<div class="row">
  <nav class="top-bar column" data-topbar>
 
      <ul class="title-area">
        <li class="name">
          <h1>
            <a href="/">
              <i class="fi-play-video"></i> A&B Fresh Produce Online Delivery
            </a>
          </h1>
        </li>
        <li class="toggle-topbar"><a href="#"><span>Menu</span></a></li>
      </ul>
 
      <section class="top-bar-section">
        <ul class="right">
        <%if signed_in?%>
        <li>
  <%= link_to cart_path do%>
    <i class="fi-shopping-cart"></i>
    My Cart
    (<span class="cart-count"><%=current_user.cart_count%></span>)
  <%end%>
</li>
          <li><%=link_to current_user.email, edit_user_registration_path%></li>
         <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
  <%else%>
    <li><%=link_to "Register", new_user_registration_path%></li>
    <li><%=link_to "Login", new_user_session_path%></li>
  <%end%>
        </ul>
      </section>
 
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:item) ? yield(:item) : "A&B Fresh Produce Online Delivery" %></title>
    <%= include_gon %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%#= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<%= render "layouts/header" %>
 
  <%= render "layouts/alerts" %>
 
  <div id="main-content" class="row full-min-height">
    <%= yield %>
  </div>
 
  <footer class="row">
    <div class="large-12 columns">
      <hr> <p>© A&B Fresh Produce Online Delivery 2015</p>
    </div>
  </footer>
 
  <%= javascript_include_tag "application" %>


  </body>
</html>

app/views/transactions/_customer_form.html.erb
<p>Please enter your personal info:</p>
<div class="mb1">
  <%= text_field_tag :first_name, "",placeholder: "First Name", class: "radius" %>
</div>
<div class="mb1">
  <%= text_field_tag :last_name, "",placeholder: "Last Name", class: "radius" %>
</div>
<!--div class="mb1"-->
  <%#= text_field_tag :company, "",placeholder: "Company", class: "radius" %>
<!--/div-->
<div class="mb1">
  <%= text_field_tag :phone, "",placeholder: "Phone", class: "radius" %>
</div>

app/views/transactions/new.html.erb
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
  <h2 class="mbs">New Transaction</h2>
<%= form_tag transactions_path do%>
  <%= render 'customer_form' unless current_user.has_payment_info? %>
  <p>Please enter your payment details:</p>
  <div id="dropin"></div>
  <%=submit_tag "Pay #{current_user.cart_total_price}$", class: "button mt1" %>
<%end%>
</div>

<script src="https://js.braintreegateway.com/v2/braintree.js"></script>